id: AAD629C61
title: The Summoning of Longevity from Chimé Pakmé Nyingtik
type: translation
pechas:
- IF354FF44
- I31BBAE1A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:34:21.345780
  last_modified_at: 2023-01-04 12:34:21.345789
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IF354FF44/EC2F: 142F
  I31BBAE1A/C1F4: 142F
